---

dir: "unfetter-store/unfetter-socket-server"
path: "{{ prepath + dir}}"
container_name: unfetter-socket-server
image_name: "{{registry}}{{ container_name }}:{{docker_tag}}"

base_list: "certs:/etc/pki/tls/certs:ro,private-config:/usr/share/unfetter-socket-server/config/private"
dev_volume_list: ",{{ prepath }}/unfetter-store/unfetter-socket-server/src:/usr/share/unfetter-socket-server/src,{{ prepath }}/unfetter-store/unfetter-socket-server/dist:/usr/share/unfetter-socket-server/dist"
volume_list: "{{ base_list }}{{ dev_volume_list if run_mode == 'dev' else '' }}"
