sudo: true
language: python
cache: pip
python:
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y swig
  - sudo apt-get install -y libpulse-dev
install:
  - 'pip install pipenv'
  - 'pipenv install'
script:
  - 'cd ansible && ansible-lint *.yml'
