version: '2'
services:  
  unfetter-discover-gateway:
    links:
     - unfetter-ui
     - unfetter-discover-api
    volumes:
     - ./config/nginx/conf.d.angular:/etc/nginx/conf.d
  unfetter-ui:
    image: unfetter/unfetter-ui
    build: ../unfetter-ui
    container_name: unfetter-ui
    depends_on:
    - unfetter-discover-openssl
    volumes:
    - ./certs/:/etc/pki/tls/certs
    - ../unfetter-ui/src:/usr/share/unfetter-ui/src
    - ../unfetter-ui/dist:/usr/share/unfetter-ui/dist
    - ../unfetter-ui/config:/usr/share/unfetter-ui/config
    entrypoint:
    - npm
    - run
    - server:dev
  unfetter-discover-api:
    image: unfetter/unfetter-discover-api
    build: ../unfetter-discover-api
    container_name: unfetter-discover-api
    depends_on:
    - unfetter-discover-openssl
    ports:
    - "49160:3000"
    volumes:
    - ./certs/:/etc/pki/tls/certs
    - ../unfetter-discover-api/api:/usr/share/unfetter-discover-api/api
    environment:
    - STIX_API_PROTOCOL=http
    - STIX_API_HOST=cti-stix-store
    - STIX_API_PORT=3000
    - STIX_API_PATH=cti-stix-store-api
    - ENV=dev
    entrypoint:
    - npm
    - start