version: '2'
services:
  unfetter-discover-ui:
    build: ../unfetter-discover-ui
    volumes:
     - ../unfetter-discover-ui/app:/usr/share/unfetter-discover-ui/app
  cti-stix-ui:
    build: ../cti-stix-ui
    volumes:
    - ../cti-stix-ui/app:/usr/share/cti-stix-ui/app
    - ../cti-stix-ui/tests:/usr/share/cti-stix-ui/tests
  unfetter-discover-processor:
    build: ../unfetter-discover-processor
  unfetter-discover-api-explorer:
    build: ../unfetter-discover-api
    volumes:
    - ../unfetter-discover-api/test:/usr/share/unfetter-discover-api/test
    - ../unfetter-discover-api/api:/usr/share/unfetter-discover-api/api
    entrypoint:
    - npm
    - run
    - swaggerdev
  unfetter-discover-api:
    build: ../unfetter-discover-api
    entrypoint:
    - npm
    - run
    - startdev
    ports:
    - "5858:5858"    
    volumes:
    - ../unfetter-discover-api/test:/usr/share/unfetter-discover-api/test
    - ../unfetter-discover-api/api:/usr/share/unfetter-discover-api/api
  cti-stix-store:
    build: ../cti-stix-store
    volumes:
    - ../cti-stix-store/server:/usr/share/cti-stix-store/server

      
