version: '2'
services:
  unfetter-discover-ui:
    build: ../unfetter-discover-ui
    volumes:
     - ../unfetter-discover-ui/app:/usr/share/unfetter-discover-ui/app
  cti-stix-ui:
    build: ../cti-stix-ui
    volumes:
    - ../cti-stix-ui/app:/usr/share/cti-stix-ui/app
    - ../cti-stix-ui/tests:/usr/share/cti-stix-ui/tests
  unfetter-discover-processor:
    build: ../unfetter-discover-processor
  unfetter-discover-api-explorer:
    build: ../unfetter-discover-api
  unfetter-discover-api:
    build: ../unfetter-discover-api
  cti-stix-store:
    build: ../cti-stix-store
    volumes:
    - ../cti-stix-store/server:/usr/share/cti-stix-store/server

      
