
####################################################################################
#  This playbook builds a new api-config
#  playbook.
#  Specific target hosts can be built using the following:
#  ansible-playbook -i dev discover.yml
#
#
####################################################################################


- debug: msg="Forcing Reconfigure of the Private Config"
  changed_when: True  

- name: include tasks to build the private config file
  include_tasks: manage-private-config.yml
   