
####################################################################################
#  This playbook builds a new api-config
#  playbook.
#  Specific target hosts can be built using the following:
#  ansible-playbook -i dev discover.yml
#
#
####################################################################################


- name: Validate private-config volume
  docker_volume:
    name: private-config      

- name: Validate ui-config volume
  docker_volume:
    name: ui-config      



- name: Run api_configuration_tool.py file
  command: "docker run --rm -it -v private-config:/api/private -v ui-config:/ui/private -v $thepath/files/scripts/api_configuration_tool.py:/scripts/api_configuration_tool.py --name api-config python:2.7.15-alpine3.6 python /scripts/api_configuration_tool.py"
    