#  The common role is run first, and contains all containers that are pulled from
#  docker repositories that are not part of Unfetter

#  It also will run generic tasks.



# Ensure the volumes are created. 

- include_tasks: "cert-volume.yml"
- name: Create mongo-db volume
  docker_volume:
    name: mongo-db
  notify:
    - load mongodb-vol
  when: run_action

- include_tasks: manage-private-config.yml
  when: use_uac and run_action

# We will reload every time
- name: Create ui-vol volume
  docker_volume:
    name: ui-config
  when: run_action

- include_tasks: manage-ui-config.yml
  when: use_uac and run_action


- name: Create the Docker Network - {{ docker_network_name }}
  docker_network:
    state: present
    name: "{{ docker_network_name }}"

# Debug message to show what the docker name is    
- debug:
    msg: "The network is {{ docker_network_name }}"


- meta: flush_handlers
# Create the cti-stix-store-repository docker container


- name: Create Repository
  docker_container:
    name: cti-stix-store-repository
    image: "mongo:3.4.1"
    state: started
    networks:
      - name: "{{ docker_network_name }}"          
    
    # Since the repository is a mongodb, we always pull
    pull: true
    volumes:
#    - "{{ prepath }}/unfetter/data/db:/data/db"
    - "mongo-db:/data/db"
    published_ports: "{{ '27018:27017' if 'development' in group_names else [] }}"

  when: run_action
    

