  - name: Generate RSA keys at {{ key_location }}
    delegate_to: localhost
    command : 'ssh-keygen -q -t rsa -f {{ ansible_ssh_private_key_file }} -C "" -N ""'
    args:
       creates: "{{ ansible_ssh_private_key_file }}"
