  - name: Generate RSA keys at {{ key_location }}
    delegate_to: localhost
<<<<<<< HEAD
    command : 'ssh-keygen -q -t rsa -f /home/srmccul/.ssh/ansible -C "" -N ""'
    args:
       creates: /home/srmccul/.ssh/ansible 
=======
    command : 'ssh-keygen -q -t rsa -f {{ ansible_ssh_private_key_file }} -C "" -N ""'
    args:
       creates: "{{ ansible_ssh_private_key_file }}"
>>>>>>> f4ca231621f58e8789e1ed892ea89a2f84f182c0
