####################################################################################
#  This playbook builds, but does not deploy, docker containers.   It will 
#  also build the production UI versions.
#
####################################################################################

- name: Build the Docker images only.
  hosts: build
  tasks:
    - name: Start running the commands
      import_tasks: discover-tasks.yml
    - include_role:
        name: gateway
        tasks_from: task-build-release
      vars:
        gateway_tag: "{{ docker_tag }}"
