####################################################################################
####################################################################################

- name: Delete Images in registry
  hosts: registry
  tasks:
    - name: Remove images
      shell: "docker rmi $(docker images -q)"
      ignore_errors: yes
      tags:
      - skip_ansible_lint

- name: Removes images and containers from target hosts
  hosts: deployed
  tasks:
    - name: Stop containers
      shell: "docker stop $(docker ps -a -q)"
      ignore_errors: yes
      tags:
      - skip_ansible_lint


    - name: Remove containers
      shell: "docker rm $(docker ps -a -q)"
      ignore_errors: yes
      tags:
      - skip_ansible_lint


    - name: Remove images
      shell: "docker rmi $(docker images -q)"
      ignore_errors: yes
      tags:
      - skip_ansible_lint


- name: Checking out all the code
  var:
    clone_branch: "{{ branch | default('develop') }}"
  import_playbook: task-checkout-code.yml branch={{ clone_branch }}


- name: Build The images
  import_playbook: build-prod.yml

- name: Push to registry
  import_playbook: task-push-registry.yml

- name: Clear the other systems
  import_playbook: task-clear-containers.yml

- name: Deploy systems
  import_playbook: deploy.yml
