####################################################################################
# Task Build Deploy will automate the creation of a clean, newly built docker containers
#    This is best for a production environment that will be building from code for testing
#
#   - Removes all docker containers and images
#   - Checks out the latest develop branch
#   - Builds the docker images 
#   - Pushes the images to a docker registry
#   - Deploys the images to hosts
####################################################################################

- name: Removes images and containers from target hosts
  hosts: deployed
  tasks:
    - include_tasks: "task-print-variables.yml"  
    - name: Stop containers
      shell: "docker stop $(docker ps -a -q)"
      ignore_errors: yes
      tags:
      - skip_ansible_lint


    - name: Remove containers
      shell: "docker rm $(docker ps -a -q)"
      ignore_errors: yes
      tags:
      - skip_ansible_lint


    - name: Remove images
      shell: "docker rmi $(docker images -q)"
      ignore_errors: yes
      tags:
      - skip_ansible_lint


- name: Checking out all the code
  import_playbook: task-checkout-code.yml

- name: Build The images
  import_playbook: build-prod.yml

- name: Push to registry
  import_playbook: task-push-registry.yml

- name: Clear the other systems
  import_playbook: task-clear-containers.yml

- name: Deploy systems
  import_playbook: deploy.yml
