---
####################################################################################
#  This playbook only builds the docker images locally
#
####################################################################################


- name: Pushes local images to a registry
  hosts: build
#  become: true
  vars:
    registry: "unfetter/"
    #docker_tag: "0.3.9"
    image_list:
         - "unfetter-api-explorer"
         - "unfetter-discover-processor"
         - "unfetter-discover-api"
         - "unfetter-ui"
         - "unfetter-ctf-ingest"
         - "unfetter-pattern-handler"
         - "unfetter-socket-server"

    gateway_config:
         - "uac"
         - "legacy.uac"
         - "legacy.demo"
         - "demo"
    latest: false
  tasks:
    - name: Build running containers for every image besides gateway
      docker_container:
        name: "{{ item }}.ready-to-export"
        image: "{{ item }}:{{ docker_tag }}"
        state: started
        entrypoint:
           - ls /tmp
      with_items: "{{ image_list }}"
      
    - name: Build running containers for every gateway
      docker_container:
        name: "unfetter-discover-gateway.{{ item }}.ready-to-export"
        image: "unfetter-discover-gateway:{{ docker_tag }}.{{ item }}"
        state: started
        entrypoint:
           - ls /tmp
      with_items: "{{ gateway_config }}"  

    - name: Exporting the Images to tar
      command: "docker export -o {{ item }}.ready-to-export.tar {{ item }}.ready-to-export"
      with_items: "{{ image_list }}"


    - name: Exporting the Gateway Images to tar
      command: "docker export -o unfetter-discover-gateway.{{ item }}.ready-to-export.tar unfetter-discover-gateway.{{ item }}.ready-to-export"
      with_items: "{{ gateway_config }}"


    - name: Import the Images
      command: docker import {{ item }}.ready-to-export.tar  {{ item }}:{{ docker_tag }}
      with_items: "{{ image_list }}"

    - name: Import the Gateway Images
      command: docker import unfetter-discover-gateway.{{ item }}.ready-to-export.tar  unfetter-discover-gateway:{{ docker_tag }}.{{ item }}
      with_items: "{{ gateway_config }}"


    - name: Tagging with Latest
      command: "docker tag {{ item }}:{{ docker_tag }}.squashed {{ registry }}{{ item }}:latest"
      with_items: "{{ image_list }}"
      when: latest

    - name: Tagging gateway with latest
      command: "docker tag unfetter-discover-gateway:{{ docker_tag }}.demo {{ registry }}unfetter-discover-gateway:latest"
      when: latest
  
    - name: Tagging with {{ next_tag }}
      command: "docker tag {{ item }}:{{ docker_tag }} {{ registry }}{{ item }}:{{ docker_tag }}"
      with_items: "{{ image_list }}"       

    - name: Tagging Gateway with {{ next_tag }}
      command: "docker tag unfetter-discover-gateway:{{ docker_tag }}.{{ item }} {{ registry }}unfetter-discover-gateway:{{ docker_tag }}.{{ item }}"
      with_items: "{{ gateway_config }}"


    - name: Pushing to {{ registry }}
      command: "docker push {{ registry }}{{ item }}:{{ docker_tag }}"
      with_items: "{{ image_list }}"

    - name: Pushin Gateway with {{ registry }}
      command: "docker push {{ registry }}unfetter-discover-gateway:{{ docker_tag }}.{{ item }}"
      with_items: "{{ gateway_config }}"

 
