---
####################################################################################
#  This playbook will upgrade from 0.3.6 to 0.3.7
#
####################################################################################
- name: Upgrades Unfetter to support version 0.3.7
  hosts: deployed
  tasks:
    - include_role:
          name: common
          tasks_from: migrate-0.3.7.yml
    - include_role:
          name: common
          tasks_from: restart-container.yml


