---
####################################################################################
#  This playbook stops and removes all docker images and containers
####################################################################################


- name: Removes images and containers from target hosts
  hosts: deployed
  tasks:


    - name: Stop containers
      shell: "docker stop $(docker ps -a -q)"
      ignore_errors: yes

    - name: Remove containers
      shell: "docker rm $(docker ps -a -q)"
      ignore_errors: yes

    - name: Remove images
      shell: "docker rmi $(docker images -q)"
      ignore_errors: yes
