---
####################################################################################
#  This playbook only builds the docker images locally
#
#  You are required to pass in two extra-vars.  
#  
#  registry: is the docker registry where to push the newly built images. "unfetter" for 
#     production push, or another registry for testing, internal staging, etc.
#
#  docker_tag: this is the docker tag we are tagging the images.  it is a parameter
#     rather than rely on the normally built in role so that we have complete control over 
#     versioning
#
#  push_latest: Do you want a latest tag to be created and pushed to the registry? Default is 
#     no.  Pass in "yes" to build and push a latest
#
#  example:    ansible-playbook task-push-registry.yml -e "push_registry=unfetter push_docker_tag=0.3.9 push_latest=yes"
####################################################################################


- name: Pushes local images to a registry
  hosts: build
#  become: true
  vars:
    #push_registry: []
    #push_docker_tag: []
    push_latest: no
    image_list:
         - "unfetter-api-explorer"
         - "unfetter-discover-processor"
         - "unfetter-discover-api"
         - "unfetter-ui"
         - "unfetter-ctf-ingest"
         - "unfetter-pattern-handler"
         - "unfetter-socket-server"
    gateway_config:
         - "uac"
         - "legacy.uac"
         - "legacy.demo"
         - "demo"
    latest: false

  tasks:
    - debug:
        msg: Building version {{ push_docker_tag }} to registry {{ push_registry }}
      when: (push_docker_tag is defined) and (push_registry is defined)

    - fail: 
        msg: "Bailing because you did not include either push_docker_tag or push_registry"
      when: not ((push_docker_tag is defined) and (push_registry is defined))

    - fail: 
        msg: "Do not put , between your variables"
      when: (push_docker_tag is search(",")) or (push_registry is search(","))

    #- meta: end_play

    - name: Build running containers for every image besides gateway
      docker_container:
        name: "{{ item }}.ready-to-export"
        image: "{{ item }}:{{ push_docker_tag }}"
        state: started
        entrypoint:
           - ls /tmp
      with_items: "{{ image_list }}"
      
    - name: Build running containers for every gateway
      docker_container:
        name: "unfetter-discover-gateway.{{ item }}.ready-to-export"
        image: "unfetter-discover-gateway:{{ push_docker_tag }}.{{ item }}"
        state: started
        entrypoint:
           - ls /tmp
      with_items: "{{ gateway_config }}"  

    - name: Exporting the Images to tar
      command: "docker export -o {{ item }}.ready-to-export.tar {{ item }}.ready-to-export"
      with_items: "{{ image_list }}"


    - name: Exporting the Gateway Images to tar
      command: "docker export -o unfetter-discover-gateway.{{ item }}.ready-to-export.tar unfetter-discover-gateway.{{ item }}.ready-to-export"
      with_items: "{{ gateway_config }}"


    - name: Import the Images
      command: docker import {{ item }}.ready-to-export.tar  {{ item }}:{{ push_docker_tag }}
      with_items: "{{ image_list }}"

    - name: Import the Gateway Images
      command: docker import unfetter-discover-gateway.{{ item }}.ready-to-export.tar  unfetter-discover-gateway:{{ push_docker_tag }}.{{ item }}
      with_items: "{{ gateway_config }}"


    - name: Tagging with Latest
      command: "docker tag {{ item }}:{{ push_docker_tag }}.squashed {{ push_registry }}{{ item }}:latest"
      with_items: "{{ image_list }}"
      when: latest

    - name: Tagging gateway with latest
      command: "docker tag unfetter-discover-gateway:{{ push_docker_tag }}.demo {{ push_registry }}unfetter-discover-gateway:latest"
      when: latest
  
    - name: Tagging with {{ next_tag }}
      command: "docker tag {{ item }}:{{ push_docker_tag }} {{ push_registry }}{{ item }}:{{ push_docker_tag }}"
      with_items: "{{ image_list }}"       

    - name: Tagging Gateway with {{ next_tag }}
      command: "docker tag unfetter-discover-gateway:{{ push_docker_tag }}.{{ item }} {{ push_registry }}unfetter-discover-gateway:{{ push_docker_tag }}.{{ item }}"
      with_items: "{{ gateway_config }}"


    - name: Pushing to {{ push_registry }}
      command: "docker push {{ push_registry }}{{ item }}:{{ push_docker_tag }}"
      with_items: "{{ image_list }}"

    - name: Pushin Gateway with {{ push_registry }}
      command: "docker push {{ push_registry }}unfetter-discover-gateway:{{ push_docker_tag }}.{{ item }}"
      with_items: "{{ gateway_config }}"

 
