---
####################################################################################
#  This playbook will upgrade from 0.3.10 to 0.3.11  
#
####################################################################################

- name: Upgrades Unfetter to support version 0.3.11
  hosts: deployed
  tasks:
    - include_role:
          name: common
          tasks_from: migrate-0.3.11.yml