---
####################################################################################
#  This playbook will upgrade from 0.3.6 to 0.3.9  
#
####################################################################################

- name: Upgrades Unfetter to support version 0.3.9
  hosts: deployed
  tasks:
    - include_role:
          name: common
          tasks_from: migrate-0.3.9.yml